export const roommates = [
  {
    id: 1,
    nickname: '하늘별',
    gender: '여성',
    mbti: 'ENFP',
    department: '컴퓨터공학과',
    year: '2학년',
    roomType: '2인실',
    sociability: 4,
    cleanliness: 5,
    smoking: false,
    indoorEating: true,
    sleepHabit: '일찍 자요 (22시 ~ 00시)',
    sleepPattern: '잠버릇 없어요',
    matchingStatus: '매칭 대기중',
    message:
      '안녕하세요! 깔끔하고 활발한 성격입니다. 함께 즐겁게 생활할 룸메이트를 찾고 있어요 😊',
  },
  {
    id: 2,
    nickname: '구름달',
    gender: '여성',
    mbti: 'ISTJ',
    department: '경영학과',
    year: '3학년',
    roomType: '2인실',
    sociability: 2,
    cleanliness: 4,
    smoking: false,
    indoorEating: false,
    sleepHabit: '일찍 자요 (22시 ~ 00시)',
    sleepPattern: '잠꼬대 해요',
    noise: '조용한걸 원해요',

    matchingStatus: '매칭 대기중',
    message:
      '조용한 환경을 선호하며 서로의 사생활을 존중하는 룸메이트를 원합니다.',
  },
  {
    id: 3,
    nickname: '바다파도',
    gender: '남성',
    mbti: 'INTP',
    department: '물리학과',
    year: '1학년',
    roomType: '4인실',
    sociability: 3,
    cleanliness: 3,
    smoking: false,
    indoorEating: true,
    sleepHabit: '늦게 자요 (00시 ~ 03시)',
    sleepPattern: '이갈이 해요',
    noise: '짧은 통화 정도만 원해요',
    matchingStatus: '매칭 대기중',
    message:
      '물리학과 1학년입니다. 공부에 집중할 수 있는 환경을 만들어가고 싶어요!',
  },
  {
    id: 4,
    nickname: '숲속나무',
    gender: '남성',
    mbti: 'ESFJ',
    department: '화학공학과',
    year: '4학년',
    roomType: '2인실',
    sociability: 5,
    cleanliness: 4,
    smoking: true,
    indoorEating: true,
    sleepHabit: '불규칙해요',
    sleepPattern: '잠꼬대 해요',
    noise: '소음 상관 없어요',
    matchingStatus: '매칭 대기중',
    message:
      '친목을 중시하고 함께 시간을 보내는 것을 좋아합니다. 서로 도움이 되는 관계였으면 좋겠어요.',
  },
  {
    id: 5,
    nickname: '산들바람',
    gender: '여성',
    mbti: 'INFJ',
    department: '심리학과',
    year: '2학년',
    roomType: '4인실',
    sociability: 3,
    cleanliness: 5,
    smoking: false,
    indoorEating: false,
    sleepHabit: '늦게 자요 (00시 ~ 03시)',
    sleepPattern: '잠버릇 없어요',
    noise: '소음 상관 없어요',

    matchingStatus: '매칭 대기중',
    message:
      '깔끔한 환경을 중요하게 생각하며, 서로 배려하는 마음으로 생활하고 싶습니다.',
  },
];
