export const posts = [
  {
    id: 1,
    title: '기숙사 생활 꿀팁 공유합니다',
    content: '기숙사에서 생활하면서 알게 된 꿀팁들을 공유합니다...',
    author: '익명',
    category: '꿀팁',
    createdAt: '2023-05-20',
    likes: 24,
    comments: 5,
  },
  {
    id: 2,
    title: '룸메이트와 잘 지내는 방법',
    content: '처음 만난 룸메이트와 어떻게 하면 잘 지낼 수 있을까요?',
    author: '익명',
    category: '친목',
    createdAt: '2023-05-19',
    likes: 18,
    comments: 12,
  },
  {
    id: 3,
    title: '기숙사 세탁기 사용 시간대 추천',
    content: '사람이 적은 시간대에 세탁기를 사용하고 싶다면...',
    author: '익명',
    category: '꿀팁',
    createdAt: '2023-05-18',
    likes: 32,
    comments: 8,
  },
  {
    id: 4,
    title: '오늘 저녁 같이 먹을 사람?',
    content: '오늘 저녁 학생식당에서 같이 밥 먹을 사람 구해요~',
    author: '익명',
    category: '친목',
    createdAt: '2023-05-17',
    likes: 7,
    comments: 15,
  },
  {
    id: 5,
    title: '기숙사 와이파이 연결 문제',
    content:
      '최근에 기숙사 와이파이 연결이 자주 끊기는데 같은 문제 겪는 분 있나요?',
    author: '익명',
    category: '자유',
    createdAt: '2023-05-16',
    likes: 41,
    comments: 23,
  },
];
